---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    name: shipping
    tier: app
spec:
  containers:
    - name: shipping
      image: jayadeep2702/shipping:k8
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: shipping-config
      resources:
        requests:
          cpu: "300m"
          memory: "200Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    name: shipping
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080