apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
  REDIS_HOST: "redis"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: app
spec:
  containers:
    - name: user
      image: jayadeep2702/user:k8
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: user-config
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "120m"
          memory: "120Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    name: user
    tier: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080