
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    tier: db
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: Always
      ports:
        - containerPort: 6379
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "120m"
          memory: "120Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
    tier: db
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 6379